# config
cover: /img/bg_img.jpg
logo: /img/logo.png
top_saying:
- title: Merry Xmas!
- content: 每一个不曾起舞的日子都是对生命的辜负。
bottom_saying: 每一个不曾起舞的日子都是对生命的辜负。
# Content
excerpt_link: Read More
rss: /atom.xml
highlightjs: vs

#Works
#works:
#- works_name: AAA
#  works_url: /

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/
google: https://google.com/

#about  timeline
timeline:
- num: 1
  word: 2018/06/12 - Start
- num: 2
  word: 2018/09/03 - Next
#- num: 3
#  word: 2015/02/18-DDD
- num: X
  word: More

#Links
links:
- name: CharlesCai
  link: 

# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: false
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 2

